# Project data processing

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('project_data.csv', header=[0]);
df.head()

,asset_type,asset_make,asset_model,asset,industry,store_performer,inspection_type,inspector,asset_owner,original_checklist,original_inspection,last_performed_inspector,last_performed_inspection_result,days_since_last_performed,inspection_result
0,a0320b75-133d-4d3e-9261-40d44435cbd3,6fafe6a6-b718-444f-ab97-0175413cb3f0,6e3e2fae-7025-41b0-a76c-d9fe729ebd38,aa3bbf52-56ea-4818-b8ae-0d61df9f8f65,469e2983-4ae0-41b5-9f3e-6c5bed400611,7657f8e9-8194-47a7-96cc-46bb9e4e2666,a6a32b6d-3c1e-4bf2-8e40-4d84e52e8cfb,bfeee75b-70e2-42cc-8976-b82a68ae1b44,fc5c9c2c-dec7-4c39-8d73-53ee8ef4655a,c00a9f82-ef6a-4e44-80dd-b041992ae5eb,2fa81b49-dc92-4c34-9748-a471b4fc1e28,d6fb490e-c1cb-4839-9727-12e14972ecea,1.0,8,1
1,a0320b75-133d-4d3e-9261-40d44435cbd3,6fafe6a6-b718-444f-ab97-0175413cb3f0,6e3e2fae-7025-41b0-a76c-d9fe729ebd38,aa3bbf52-56ea-4818-b8ae-0d61df9f8f65,469e2983-4ae0-41b5-9f3e-6c5bed400611,7657f8e9-8194-47a7-96cc-46bb9e4e2666,a6a32b6d-3c1e-4bf2-8e40-4d84e52e8cfb,bfeee75b-70e2-42cc-8976-b82a68ae1b44,fc5c9c2c-dec7-4c39-8d73-53ee8ef4655a,c00a9f82-ef6a-4e44-80dd-b041992ae5eb,2fa81b49-dc92-4c34-9748-a471b4fc1e28,d6fb490e-c1cb-4839-9727-12e14972ecea,1.0,8,1
2,a0320b75-133d-4d3e-9261-40d44435cbd3,6fafe6a6-b718-444f-ab97-0175413cb3f0,6e3e2fae-7025-41b0-a76c-d9fe729ebd38,aa3bbf52-56ea-4818-b8ae-0d61df9f8f65,469e2983-4ae0-41b5-9f3e-6c5bed400611,7657f8e9-8194-47a7-96cc-46bb9e4e2666,a6a32b6d-3c1e-4bf2-8e40-4d84e52e8cfb,bfeee75b-70e2-42cc-8976-b82a68ae1b44,fc5c9c2c-dec7-4c39-8d73-53ee8ef4655a,c00a9f82-ef6a-4e44-80dd-b041992ae5eb,2fa81b49-dc92-4c34-9748-a471b4fc1e28,d6fb490e-c1cb-4839-9727-12e14972ecea,1.0,8,1
3,a0320b75-133d-4d3e-9261-40d44435cbd3,6fafe6a6-b718-444f-ab97-0175413cb3f0,6e3e2fae-7025-41b0-a76c-d9fe729ebd38,aa3bbf52-56ea-4818-b8ae-0d61df9f8f65,469e2983-4ae0-41b5-9f3e-6c5bed400611,7657f8e9-8194-47a7-96cc-46bb9e4e2666,a6a32b6d-3c1e-4bf2-8e40-4d84e52e8cfb,bfeee75b-70e2-42cc-8976-b82a68ae1b44,fc5c9c2c-dec7-4c39-8d73-53ee8ef4655a,c00a9f82-ef6a-4e44-80dd-b041992ae5eb,2fa81b49-dc92-4c34-9748-a471b4fc1e28,d6fb490e-c1cb-4839-9727-12e14972ecea,1.0,8,1
4,a0320b75-133d-4d3e-9261-40d44435cbd3,6fafe6a6-b718-444f-ab97-0175413cb3f0,6e3e2fae-7025-41b0-a76c-d9fe729ebd38,ea0377c6-0b23-43f3-8d0c-b14bd65a3b66,469e2983-4ae0-41b5-9f3e-6c5bed400611,7657f8e9-8194-47a7-96cc-46bb9e4e2666,a6a32b6d-3c1e-4bf2-8e40-4d84e52e8cfb,bfeee75b-70e2-42cc-8976-b82a68ae1b44,fc5c9c2c-dec7-4c39-8d73-53ee8ef4655a,c00a9f82-ef6a-4e44-80dd-b041992ae5eb,2fa81b49-dc92-4c34-9748-a471b4fc1e28,7f58ce03-9a95-463f-93fc-2df330d52788,1.0,31,1

## Dealing with missing values

In [3]:
# Check first for missing values
print(df.isnull().sum())

asset_type                            27
asset_make                            22
asset_model                            0
asset                                  0
industry                            1146
store_performer                        0
inspection_type                        0
inspector                              0
asset_owner                          348
original_checklist                     0
original_inspection                    0
last_performed_inspector               0
last_performed_inspection_result      40
days_since_last_performed              0
inspection_result                      0
dtype: int64

All the next code was commented out since it made the quantity of samples too big. The missing values for this features were removed on data extraction query.

In [4]:
# Fill missing values on days_since_last_performed with the median of the asset_model column
# Calculate the median for each model
#grouped_medians = df.groupby("asset_model")["days_since_last_performed"].median()

# Fill missing values based on the median of the corresponding group
#df["days_since_last_performed"].fillna(df["asset_model"].map(grouped_medians), inplace=True)

# Fill missing values in last_performed_inspector with the mode of the store_performer column
# Calculate the median for each model
#grouped_modes = df.groupby("store_performer")["last_performed_inspector"].apply(lambda x: x.mode().iloc[0] if not x.mode().empty else None)

# Fill missing values based on the mode of the corresponding group
#df["last_performed_inspector"].fillna(df["store_performer"].map(grouped_modes), inplace=True)

#print(df.isnull().sum())

In [5]:
# Fill missing values with the median of the column in place
#df["days_since_last_performed"].fillna(df["days_since_last_performed"].median(), inplace=True)

#df["last_performed_inspector"].fillna(df["last_performed_inspector"].mode()[0], inplace=True)
#print(df.isnull().sum())

In [6]:
# Dropping missing values, reseting indexes (important for next steps) and printing new shape
df = df.dropna(axis=0)
df.reset_index(drop=True, inplace=True)
df.shape

(61869, 15)

## Scaling data

In [7]:
# The only feature we need to scale is the ´days_since_last_performed' since everything else is normalized with 0s and 1s
from sklearn.preprocessing import StandardScaler, MinMaxScaler

# Initialize the MinMaxScaler
scaler = MinMaxScaler(feature_range=(0, 1))

# Fit and transform the selected column
column_values = df['days_since_last_performed'].values.reshape(-1, 1)
df['days_since_last_performed'] = scaler.fit_transform(column_values)

# Display the normalized DataFrame
df['days_since_last_performed']

0        0.005857
1        0.005857
2        0.005857
3        0.005857
4        0.022694
           ...
61864    0.020498
61865    0.132504
61866    0.073939
61867    0.001464
61868    0.073939
Name: days_since_last_performed, Length: 61869, dtype: float64

## Dealing with categorical data

In [8]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=False)

columns_order = df.columns.tolist()

categorical_cols = [
    'asset',
    'asset_type',
    'asset_make',
    'asset_model',
    'industry',
    'store_performer',
    'inspection_type',
    'inspector',
    'asset_owner',
    'last_performed_inspector',
    'original_inspection',
    'original_checklist',
    'last_performed_inspection_result'
]

for i, col in enumerate(categorical_cols):
    # Get the index from the column order
    index = columns_order.index(col)
    # Encode data
    encoded_data = encoder.fit_transform(df[[col]])
    # Get columns of the enconded DataFrame
    feature_names = encoder.get_feature_names_out([col])
    # Convert the encoded data to a DataFrame with column names
    encoded_df = pd.DataFrame(encoded_data, columns=feature_names)
    # Remove categorical column from original DataFrame
    df.drop([col], axis=1, inplace=True)
    # Add the new encoded columns
    df = pd.concat([df, encoded_df], axis=1)
    # Remove categorical column from the columns order
    del columns_order[index]
    # Add all the new encoded columns to the columns order at the right index
    for j, enco_col in enumerate(encoded_df.columns):
        columns_order.insert(index, enco_col)
        index += 1

# Apply correct order to DataFrame
df = df[columns_order]
print(len(columns_order))

33976

## Dimentionality reduction

In [9]:
import keras
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Model
from sklearn.model_selection import train_test_split

X = df.iloc[:,:-3].values

# Split the data into training and testing sets
X_train, X_test = train_test_split(X, test_size=0.2, random_state=42)

# Define the architecture of the encoder
input_size = X_train.shape[1]

input_data = Input(shape=(input_size,))
encoding_dim = 1024

# Encoder layers
encoded = Dense(8192, activation='tanh')(input_data)
encoded = Dense(4096, activation='tanh')(encoded)
encoded = Dense(encoding_dim, activation='tanh')(encoded)

# Decoder layers
decoded = Dense(4096, activation='tanh')(encoded)
decoded = Dense(8192, activation='tanh')(decoded)
decoded = Dense(input_size, activation='sigmoid')(decoded)

autoencoder = Model(inputs=input_data, outputs=decoded)

# Compile the autoencoder model
autoencoder.compile(optimizer='adam', loss='binary_crossentropy')
autoencoder.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input_1 (InputLayer)        [(None, 33973)]           0

 dense (Dense)               (None, 8192)              278315008

 dense_1 (Dense)             (None, 4096)              33558528

 dense_2 (Dense)             (None, 1024)              4195328

 dense_3 (Dense)             (None, 4096)              4198400

 dense_4 (Dense)             (None, 8192)              33562624

 dense_5 (Dense)             (None, 33973)             278340789

=================================================================
Total params: 632170677 (2.36 GB)
Trainable params: 632170677 (2.36 GB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [10]:
# Train the autoencoder on the categorical data
autoencoder.fit(X_train, X_train, epochs=5, batch_size=32, shuffle=True, validation_data=(X_test, X_test))

Epoch 1/5
1547/1547 [==============================] - 1079s 696ms/step - loss: 0.0050 - val_loss: 0.0041
Epoch 2/5
1547/1547 [==============================] - 1100s 710ms/step - loss: 0.0044 - val_loss: 0.0053
Epoch 3/5
1547/1547 [==============================] - 1097s 708ms/step - loss: 0.0050 - val_loss: 0.0048
Epoch 4/5
1547/1547 [==============================] - 1649s 1s/step - loss: 0.0050 - val_loss: 0.0052
Epoch 5/5
1547/1547 [==============================] - 1035s 668ms/step - loss: 0.0050 - val_loss: 0.0051

In [16]:
# Evaluate the model on the test set
evaluation_results = autoencoder.evaluate(X_test, X_test)

# Display evaluation results
print(f"Loss: {evaluation_results}")

387/387 [==============================] - 51s 128ms/step - loss: 0.0051
Loss: 0.005106734111905098

In [12]:
# Create the model with only the encoding layers
encoder_model = Model(inputs=input_data, outputs=encoded)

# Encode all features
reduced_features_train = encoder_model.predict(X_train)
reduced_features_test = encoder_model.predict(X_test)

1547/1547 [==============================] - 107s 68ms/step
387/387 [==============================] - 27s 68ms/step

In [13]:
# Create DataFrames for reduced features
reduced_df_train = pd.DataFrame(reduced_features_train, columns=[f"encoded_{i+1}" for i in range(encoding_dim)])
reduced_df_test = pd.DataFrame(reduced_features_test, columns=[f"encoded_{i+1}" for i in range(encoding_dim)])

# Concatenate reduced feature DataFrames
reduced_combined = pd.concat([reduced_df_train, reduced_df_test], axis=0, ignore_index=True)
reduced_combined

,encoded_1,encoded_2,encoded_3,encoded_4,encoded_5,encoded_6,encoded_7,encoded_8,encoded_9,encoded_10,...,encoded_1015,encoded_1016,encoded_1017,encoded_1018,encoded_1019,encoded_1020,encoded_1021,encoded_1022,encoded_1023,encoded_1024
0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,-0.993049,0.990783,-1.0,-1.0,1.0,-1.0,1.000000,-1.0,1.0,-1.000000
1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,-0.993037,0.992772,-1.0,-1.0,1.0,-1.0,1.000000,-1.0,1.0,-1.000000
2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,-0.993227,0.992398,-1.0,-1.0,1.0,-1.0,1.000000,-1.0,1.0,-1.000000
3,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,-0.991815,0.989226,-1.0,-1.0,1.0,-1.0,1.000000,-1.0,1.0,-1.000000
4,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,-0.993121,0.993049,-1.0,-1.0,1.0,-1.0,1.000000,-1.0,1.0,-1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61864,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,-0.976977,0.967954,-1.0,-1.0,1.0,-1.0,0.999994,-1.0,1.0,-0.999999
61865,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,-0.993430,0.992276,-1.0,-1.0,1.0,-1.0,1.000000,-1.0,1.0,-1.000000
61866,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,-0.993096,0.992359,-1.0,-1.0,1.0,-1.0,1.000000,-1.0,1.0,-1.000000
61867,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,-0.992641,0.990399,-1.0,-1.0,1.0,-1.0,1.000000,-1.0,1.0,-1.000000
61868,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,-0.993428,0.991961,-1.0,-1.0,1.0,-1.0,1.000000,-1.0,1.0,-1.000000

In [14]:
# Choose the two columns to concatenate from the original DataFrame
columns_to_concat = ["days_since_last_performed", "inspection_result"]

# Concatenate the selected columns with the reduced_combined DataFrame
reduced_df = pd.concat([reduced_combined, df[columns_to_concat]], axis=1)
reduced_df

,encoded_1,encoded_2,encoded_3,encoded_4,encoded_5,encoded_6,encoded_7,encoded_8,encoded_9,encoded_10,...,encoded_1017,encoded_1018,encoded_1019,encoded_1020,encoded_1021,encoded_1022,encoded_1023,encoded_1024,days_since_last_performed,inspection_result
0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,-1.0,-1.0,1.0,-1.0,1.000000,-1.0,1.0,-1.000000,0.005857,1
1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,-1.0,-1.0,1.0,-1.0,1.000000,-1.0,1.0,-1.000000,0.005857,1
2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,-1.0,-1.0,1.0,-1.0,1.000000,-1.0,1.0,-1.000000,0.005857,1
3,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,-1.0,-1.0,1.0,-1.0,1.000000,-1.0,1.0,-1.000000,0.005857,1
4,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,-1.0,-1.0,1.0,-1.0,1.000000,-1.0,1.0,-1.000000,0.022694,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61864,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,-1.0,-1.0,1.0,-1.0,0.999994,-1.0,1.0,-0.999999,0.020498,2
61865,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,-1.0,-1.0,1.0,-1.0,1.000000,-1.0,1.0,-1.000000,0.132504,1
61866,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,-1.0,-1.0,1.0,-1.0,1.000000,-1.0,1.0,-1.000000,0.073939,1
61867,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,-1.0,-1.0,1.0,-1.0,1.000000,-1.0,1.0,-1.000000,0.001464,2
61868,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,-1.0,-1.0,1.0,-1.0,1.000000,-1.0,1.0,-1.000000,0.073939,1

## Save the data on csv

In [1]:
# Uncomment to save csv after processing (this will overwrite if a file with the same name already exists)
#reduced_df.to_csv('processed_project_data.csv', index=False)